### ISSUE TITLE
Episode 13: sampler arrays indexed with non-constant expressions are forbidden in GLSL ES 3.00 and later

### ISSUE THREAD

**Issue by truemaker** [codingminecraft/MarioYoutube#8]
OpenGL: 3.0 Mesa 20.0.8
GLSL: 1.30
Renderer: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
Vendor: Intel Open Source Technology Center
Max. Textures: 16

Error Fragment!
0:16(27): error: sampler arrays indexed with non-constant expressions are forbidden in GLSL ES 3.00 and later

Exception in thread "main" java.lang.AssertionError: 
	at render.Shader.compile(Shader.java:91)
	at engine.managment.AssetPool.getShader(AssetPool.java:20)
	at render.RenderBatch.<init>(RenderBatch.java:45)
	at render.Renderer.add(Renderer.java:37)
	at render.Renderer.add(Renderer.java:20)
	at engine.scenes.Scene.load(Scene.java:37)
	at tests.Test.load(Test.java:62)
	at render.Window.loop(Window.java:146)
	at render.Window.run(Window.java:65)
	at main.Main.main(Main.java:30)

**Comment by codingminecraft** [comment]
This code isn't meant to be compatible with GLSL ES. Buf if you want an example of how to solve this issue for ES you can either create a giant switch statement so that the indexing is a constant expression, or you may be able to do something like the getSampleFromFont function here: https://github.com/ambrosiogabe/MathAnimation/blob/master/assets/shaders/default.glsl .

**Comment by truemaker** [comment]
well 3.0 es is the only thing that works for me

**Comment by athaun** [comment]
This is also an issue with openGL core 3.3
https://github.com/athaun/Gprocessing/issues/1

**Comment by athaun** [comment]
It depends on your OS, graphics driver, and hardware if that error occurs, since some implementations of the openGL spec support it and some don't.
